FROM node:18-alpine3.18 as web-build
COPY ui ui
RUN cd ui && \
  npm install && \
  npm run build && \
  rm -rf ./node_modules

FROM harbor.qihoo.net/wfwqjs-eventing-zevent-pub/apps/maxkb-python-pg:python3.11-pg15.6

ARG DEPENDENCIES="                    \
  python3-pip"

RUN apt-get update && \
  apt-get install -y --no-install-recommends $DEPENDENCIES && \
  apt-get clean all  && \
  rm -rf /var/lib/apt/lists/*

COPY . /opt/maxkb/app
RUN mkdir -p /opt/maxkb/app /opt/maxkb/model /opt/maxkb/conf && \
  rm -rf /opt/maxkb/app/ui
COPY --from=web-build ui /opt/maxkb/app/ui
WORKDIR /opt/maxkb/app
RUN python3 -m venv /opt/py3 && \
  pip install poetry --break-system-packages && \
  poetry config virtualenvs.create false && \
  . /opt/py3/bin/activate && \
  if [ "$(uname -m)" = "x86_64" ]; then sed -i 's/^torch.*/torch = {version = "^2.2.1+cpu", source = "pytorch"}/g' pyproject.toml; fi && \
  poetry install